In [59]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
#plt.style.use("seaborn-whitegrid")
import seaborn as sns
import scipy

In [60]:
from google.colab import files
uploaded = files.upload()

Saving Egy-COVID-19.csv to Egy-COVID-19 (2).csv

In [61]:
df = pd.read_csv("Egy-COVID-19.csv")
df.head(1)

,date,new_confirmed,new_deaths,new_recovered,new_pos_to_neg,active_pos,cases_in_hospital,total_confirmed,total_deaths,total_recovered,total_pos_to_neg,lockdown,lockdown_duration
0,3/1/2020,1,0,0,0,1,1,2,0,1,1,No,0

In [62]:
#check data size
df.shape

(85, 13)

In [63]:
#check data types
df.dtypes

date                 object
new_confirmed         int64
new_deaths            int64
new_recovered         int64
new_pos_to_neg        int64
active_pos            int64
cases_in_hospital     int64
total_confirmed       int64
total_deaths          int64
total_recovered       int64
total_pos_to_neg      int64
lockdown             object
lockdown_duration     int64
dtype: object

In [64]:
#count the missing data
df.isnull().sum()

date                 0
new_confirmed        0
new_deaths           0
new_recovered        0
new_pos_to_neg       0
active_pos           0
cases_in_hospital    0
total_confirmed      0
total_deaths         0
total_recovered      0
total_pos_to_neg     0
lockdown             0
lockdown_duration    0
dtype: int64

In [65]:
## Convert the 'date' from object to datetime format
df['date']=pd.to_datetime(df['date'])
df.head(5)

,date,new_confirmed,new_deaths,new_recovered,new_pos_to_neg,active_pos,cases_in_hospital,total_confirmed,total_deaths,total_recovered,total_pos_to_neg,lockdown,lockdown_duration
0,2020-03-01,1,0,0,0,1,1,2,0,1,1,No,0
1,2020-03-02,0,0,0,0,1,1,2,0,1,1,No,0
2,2020-03-03,0,0,0,0,1,1,2,0,1,1,No,0
3,2020-03-04,0,0,0,0,1,1,2,0,1,1,No,0
4,2020-03-05,1,0,0,0,2,2,3,0,1,1,No,0

In [66]:
df.dtypes

date                 datetime64[ns]
new_confirmed                 int64
new_deaths                    int64
new_recovered                 int64
new_pos_to_neg                int64
active_pos                    int64
cases_in_hospital             int64
total_confirmed               int64
total_deaths                  int64
total_recovered               int64
total_pos_to_neg              int64
lockdown                     object
lockdown_duration             int64
dtype: object

In [68]:
#check if lockdown_duration > 0 then lockdown 'YES' else 'NO'
df['lockdown'] = np.where(df['lockdown_duration'] > 0, 'Yes', 'No')
df.head()

,date,new_confirmed,new_deaths,new_recovered,new_pos_to_neg,active_pos,cases_in_hospital,total_confirmed,total_deaths,total_recovered,total_pos_to_neg,lockdown,lockdown_duration
0,2020-03-01,1,0,0,0,1,1,2,0,1,1,No,0
1,2020-03-02,0,0,0,0,1,1,2,0,1,1,No,0
2,2020-03-03,0,0,0,0,1,1,2,0,1,1,No,0
3,2020-03-04,0,0,0,0,1,1,2,0,1,1,No,0
4,2020-03-05,1,0,0,0,2,2,3,0,1,1,No,0

In [69]:
df.dtypes

date                 datetime64[ns]
new_confirmed                 int64
new_deaths                    int64
new_recovered                 int64
new_pos_to_neg                int64
active_pos                    int64
cases_in_hospital             int64
total_confirmed               int64
total_deaths                  int64
total_recovered               int64
total_pos_to_neg              int64
lockdown                     object
lockdown_duration             int64
dtype: object

In [73]:
# Convert 'lockdown' to category
df['lockdown'] = df['lockdown'].astype('category')

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               85 non-null     datetime64[ns]
 1   new_confirmed      85 non-null     int64
 2   new_deaths         85 non-null     int64
 3   new_recovered      85 non-null     int64
 4   new_pos_to_neg     85 non-null     int64
 5   active_pos         85 non-null     int64
 6   cases_in_hospital  85 non-null     int64
 7   total_confirmed    85 non-null     int64
 8   total_deaths       85 non-null     int64
 9   total_recovered    85 non-null     int64
 10  total_pos_to_neg   85 non-null     int64
 11  lockdown           85 non-null     category
 12  lockdown_duration  85 non-null     int64
dtypes: category(1), datetime64[ns](1), int64(11)
memory usage: 8.3 KB

In [76]:
# Save the cleaned data to a new CSV file
df.to_csv('Egy-COVID-19_Cleaned.csv', index=False)